modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]]
    modId="dramaticdoors"
    version="${file.jarVersion}"
    displayName="Dramatic Doors"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dramatic-doors"
    issueTrackerURL="https://github.com/TheFizzWare/DramaticDoors/issues"
    authors="FizzWare"
    credits="Thanks to the creators of Minecraft and Forge.\n     Kitteh6660 for maintaining and updating this mod."
    description='''
    Doors that are barely tall enough to fit your player ... ?
    Doors that suffocate you when you ride ol' Blackjack the horse through? Enderman discrimination? Seriously?
    ... PAH!!

    Can we not have intrigue?  Whatever happened to the tender grace and elegance of a nice tall door? Where is the drama?!?
    Here. I have it. And now you can too.

    Gone are the ways of the past - with the new Dramatic Doors mod!

    With the modern era of innovations comes a new door type: the tall door.
    These 3-block-high doors come in every vanilla variety;
    Iron, Oak, Spruce, Birch, Acacia, Dark Oak, Jungle, Crimson, and Warped! And in 1.19, the all-new Mangrove!
    Craft one by putting 3 of the vanilla variant vertically in a crafting table.
    
    Now supports several popular mods!
    '''

[[dependencies.dramaticdoors]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.94,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="atmospheric"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="autumnity"
    mandatory=false
    versionRange="[2.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="bamboo_blocks"
    mandatory=false
    versionRange=""
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="buzzier_bees"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="caverns_and_chasms"
    mandatory=false
    versionRange="[0.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="endergetic"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="environmental"
    mandatory=false
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="upgrade_aquatic"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="abundance"
    mandatory=false
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="bayou_blues"
    mandatory=false
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="enhanced_mushrooms"
    mandatory=false
    versionRange="[4.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="architects_palette"
    mandatory=false
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="darkerdepths"
    mandatory=false
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="dustrial_decor"
    mandatory=false
    versionRange="[1.3.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="ecologics"
    mandatory=false
    versionRange="[1.5.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="habitat"
    mandatory=false
    versionRange="[1.1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="outer_end"
    mandatory=false
    versionRange="[0.2,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="quark"
    mandatory=false
    versionRange="[3.2,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="supplementaries"
    mandatory=false
    versionRange="[1.3,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="biomesoplenty"
    mandatory=false
    versionRange="[1.19,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.dramaticdoors]]
    modId="byg"
    mandatory=false
    versionRange="[2.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dramaticdoors]]
    modId="undergarden"
    mandatory=false
    versionRange="[0.7.0,)"
    ordering="AFTER"
    side="BOTH"
